### ISSUE TITLE
安装包文件缺少安装过程文件

### ISSUE THREAD

**Issue by lilinlinlin** [yunify/qingcloud-csi#92]
以下两个文件在安装包中没看到：csi-driver.yaml  
csi-controller-deploy.yaml；但是安装过程需要这两个文件

**Comment by wnxn** [comment]
开发中 qingcloud csi v1.1.0 版本安装文档在整理中，和 qingcloud csi v0.2.x 有差别。
qingcloud csi v0.2.x 安装文档可以切换到相应 tag 插件内容。
